### ISSUE TITLE
How to achieve depth reconstruction for matterport3D?

### ISSUE THREAD

**Issue by CrystalSixone** [leggedrobotics/viplanner#18]
Hi, thank you for your excellent work! Your project is very interesting, and I am particularly excited about its application for indoor visual navigation.

1. While attempting to reproduce the code for the Matterport3D dataset, I encountered an issue during the [Cost-Map Building](https://github.com/leggedrobotics/viplanner/blob/main/TRAINING.md) process. As mentioned, the depth reconstruction process requires a specific data structure, including `camera_extrinsic.txt`, `intrinsics.txt`, `depth` folders with `xxxx.png` and `xxxx.npy`, and the `semantic` folders with `xxxx.png`. I'm uncertain how to generate or obtain these data files. Could you provide guidance on this?

2. Additionally, I noticed that the `ply_file` parameter needs to be specified in the `GeneralCostMapConfig` class located in [viplanner/config/costmap_cfg.py](https://github.com/leggedrobotics/viplanner/blob/main/viplanner/config/costmap_cfg.py#L153). Could you clarify where I can find this `xxx.ply` file within the Matterport3D dataset?

I would greatly appreciate any suggestions or advice you could provide. Thank you once again for your outstanding work.

Best regards.

**Comment by pascal-roth** [comment]
Hi,

First of all thanks for using our work. To answer your points:

1. We are working on https://github.com/leggedrobotics/isaac-nav-suite (not public yet, currently updated to latest Isaac 4.0 version) which will automate the data generation and which will also have an example code for the 3D reconstruction. 

2. This ply file is delivered with the rest of the matterport files. It should be under the directory "house_segmentation" if you download the zip file for an environment. 

I hope that helps you to get started. If there are any more issues, please let us know.

**Comment by CrystalSixone** [comment]
Thank you very much! Looking forward to your new work 👍
