### ISSUE TITLE
Jetson deployed with semantic information not outputting correctly

### ISSUE THREAD

**Issue by Ruihyw** [leggedrobotics/viplanner#23]
Hi!Sry to bother you again! I'm having some problems deploying on jetson ros.
I created the container using dockerfile, after configuring the environment I connected the realsense D435i camera and modified the topic, color and depth to odom coordinate mapping I published the static transformation using "tf", then I started the program and no error was reported.
But when I try to view /viplanner/sem_image in rviz I find that the image is all black, I use rostopic echo to see that there is content output for the topic but no matter how I move the camera the content remains the same!
![2024-08-26 21-36-50 的屏幕截图](https://github.com/user-attachments/assets/26442b05-48df-47d2-bf50-4abd66580370)
"success" means that /viplanner/sem_image/Compressed has been successfully published.The reported error also stopped appearing after I released the static transforms
![2024-08-26 21-39-05 的屏幕截图](https://github.com/user-attachments/assets/12a7d542-ba49-47a1-b027-1cb2d08f142b)
Topic has output but rviz can't display it！
![2024-08-26 21-40-27 的屏幕截图](https://github.com/user-attachments/assets/cca4c673-9671-4a50-950b-afa4de360d29)

**Comment by Ruihyw** [comment]
![2024-08-28 18-12-07 的屏幕截图](https://github.com/user-attachments/assets/10b59398-c34c-413c-b902-e0f084d83249)
I have installed the extension but it still shows that :
[Warning] Pre-trained ResNet50 models cannot be used since mask2former not found
And it shows that the model dictionary is wrong like the pic above

**Comment by Ruihyw** [comment]
![2024-09-04 18-43-26 的屏幕截图](https://github.com/user-attachments/assets/637b9afd-ef51-4a1d-8f0f-9e30de457fd6)
I found the problem, the semantic segmentation module is able to read the realsense image data, but the output is all black, I used the model and parameter files recommended in Install.md, but still get this result, I'm very confused don't know how to modify it:(

**Comment by Ruihyw** [comment]
print("Result unique values:", np.unique(result)) 
output: Result unique values: [133] This means that the model partitions out only one type

**Comment by pascal-roth** [comment]
Hi, 
This is an issue with the mask2former model, more specifically, that the downloaded weights do not fit the used architecture (I guess there was a renaming of part of the network). If I remember correctly, then this was a version issue of mmcv and mmengine, as they renamed parts of the network without updating the weights. Can you make sure that you have following versions of the packages:

mmcv 2.0.0
mmdet 3.1.0
mmengine 0.8.4

**Comment by yzysmile** [comment]
> Hi, This is an issue with the mask2former model, more specifically, that the downloaded weights do not fit the used architecture (I guess there was a renaming of part of the network). If I remember correctly, then this was a version issue of mmcv and mmengine, as they renamed parts of the network without updating the weights. Can you make sure that you have following versions of the packages:
> 
> mmcv 2.0.0 mmdet 3.1.0 mmengine 0.8.4

hi,
how can i get model config about image segemantation as i just see a model included its weights in ros install

**Comment by Ruihyw** [comment]
> > Hi, This is an issue with the mask2former model, more specifically, that the downloaded weights do not fit the used architecture (I guess there was a renaming of part of the network). If I remember correctly, then this was a version issue of mmcv and mmengine, as they renamed parts of the network without updating the weights. Can you make sure that you have following versions of the packages:
> > mmcv 2.0.0 mmdet 3.1.0 mmengine 0.8.4
> 
> hi, how can i get model config about image segemantation as i just see a model included its weights in ros install

hi! For me,I have following versions of the packages 
mmcv 2.0.0 mmdet 3.1.0 mmengine 0.8.4
![image](https://github.com/user-attachments/assets/e40e2698-1e66-480e-a45f-18ecdec01eff)
The model named "Swin-B" workd! 
You can get these data here
https://github.com/open-mmlab/mmdetection/tree/master/configs/mask2former

**Comment by Ruihyw** [comment]
> Hi, This is an issue with the mask2former model, more specifically, that the downloaded weights do not fit the used architecture (I guess there was a renaming of part of the network). If I remember correctly, then this was a version issue of mmcv and mmengine, as they renamed parts of the network without updating the weights. Can you make sure that you have following versions of the packages:
> 
> mmcv 2.0.0 mmdet 3.1.0 mmengine 0.8.4

Thank you so much! I changed the model,and it's workd!
Now,should i use the "LIO" or "VIO" or anything else to provide the "odom"?

**Comment by pascal-roth** [comment]
That is up to you, basically the odom that is more precise.

**Comment by pascal-roth** [comment]
closing this issue now, as it seems to be resolved
