### ISSUE TITLE
ideas for improving cost_map to build

### ISSUE THREAD

**Issue by heyshouzi** [leggedrobotics/viplanner#24]
Can cost_map be created through online learning? like your groups's WVN paper.  When constructing cost_map, the semantic labels are associated with specific navigation effects, for example, the "grass" area where the robot may find it often difficult to navigate (determined by the relationship between desired and actual speed), thus automatically increasing the cost value of the area.

**Comment by pascal-roth** [comment]
Hi, yes, that is definitely an option, and it would be interesting to combine the two works in that way!
