### ISSUE TITLE
The adaptability of the model to camera perspectives

### ISSUE THREAD

**Issue by yzysmile** [leggedrobotics/viplanner#26]
Thanks for your the outstanding work!

The original paper mentioned that "The corresponding images at each sampled point are then rendered at angles that maximize the coverage of the traversable space." 
Does it mean capturing images in a virtual environment from different camera perspectives?

**Comment by yzysmile** [comment]
> Thanks for your the outstanding work!
> 
> The original paper mentioned that "The corresponding images at each sampled point are then rendered at angles that maximize the coverage of the traversable space." Does it mean capturing images in a virtual environment from different camera perspectives?

To be more specifically, for example, the camera's perspectives at current sample point may different from the last sample point.Is it true?

**Comment by pascal-roth** [comment]
> Thanks for your the outstanding work!
> 
> The original paper mentioned that "The corresponding images at each sampled point are then rendered at angles that maximize the coverage of the traversable space." Does it mean capturing images in a virtual environment from different camera perspectives?

Thanks a lot for using our work! 

During the sampling, we check the average distance of the depth images. To maximize the coverage of the traversable space, images are filtered where the average distance is below a certain threshold. Generally, the camera orientation will differ for each sample point, as it is sampled randomly in certain ranges. Does that answer your question.

**Comment by yzysmile** [comment]
> > Thanks for your the outstanding work!
> > The original paper mentioned that "The corresponding images at each sampled point are then rendered at angles that maximize the coverage of the traversable space." Does it mean capturing images in a virtual environment from different camera perspectives?
> 
> Thanks a lot for using our work!
> 
> During the sampling, we check the average distance of the depth images. To maximize the coverage of the traversable space, images are filtered where the average distance is below a certain threshold. Generally, the camera orientation will differ for each sample point, as it is sampled randomly in certain ranges. Does that answer your question.

Will the camera look downing during sampling as our robot has a camera looking down at an angle about 10 degree? 
As the below picture shows, red coordinate represents a camera looking down at an angle about 10 degree.
![viplanner_issue](https://github.com/user-attachments/assets/c53db710-a513-4cf4-8a24-543a42b84216)

**Comment by pascal-roth** [comment]
We also tested it with a camera looking down up to 20 degrees and added certain randomization on top of that, there seemed to be no issue

**Comment by pascal-roth** [comment]
@yzysmile did that work for you?

**Comment by pascal-roth** [comment]
closing this issue now as it seems resolved

**Comment by yzysmile** [comment]
> @yzysmile did that work for you?

yes, thanks for your reply. ☺
