### ISSUE TITLE
[Bug Report] isaac sim 4.2 simulation problem in dev/upgrade branch

### ISSUE THREAD

**Issue by heyshouzi** [leggedrobotics/viplanner#33]
Hi, after merging the dev/upgrade branch into my local copy, I tested the code and found the following issues.

In warehouse environment.

1. anymal is moving unusually slowly on way to the tagrget point as shown below.

https://github.com/user-attachments/assets/47d9f00a-d8c9-48fe-b149-4325c40af621

2.When the target point is reached,no reset option appears after clicking the pause button.

https://github.com/user-attachments/assets/884a212c-915f-41b5-b0d4-fa185a75fb30

3.Overlap of man and object
![2024-10-22 14-34-56 的屏幕截图](https://github.com/user-attachments/assets/ebeac32f-421e-49c4-ab8e-ba5a4efe8001)

In carla environment.

1. Is it unreasonable that anyaml's contact surface seems to be below the ground?

https://github.com/user-attachments/assets/b81bad47-98f7-4589-b34b-c3c39885b729

**Comment by pascal-roth** [comment]
Hi,

first of all, thanks for using our work. All your issues have been addressed in #32 

Warehouse
1) The max speed has been increased from 0.5 to 1.0
2) A reset term has been introduced to reset the robot when it reaches the goal
3) the overlab has been resolved

Carla
1) Please redownload the asset, collisions have been added to the mesh

**Comment by heyshouzi** [comment]
thanks.
