### ISSUE TITLE
viplanner isaaclab error

### ISSUE THREAD

**Issue by deavn2236** [leggedrobotics/viplanner#38]
I followed your instructions to configure isaaclab and viplanner, and wanted to try the effect under NVIDIA Warehouse. In the end, I received many warnings and isaaclab did not display. It is not a problem for me to open isaaclab normally without running the viplanner code. What is the reason for this? How can I solve it?
![2024-11-12 11-15-40屏幕截图](https://github.com/user-attachments/assets/5b0bfb31-fbc3-4b82-aa0e-588d72010f35)

**Comment by pascal-roth** [comment]
Hi @deavn2236 

First of all, thanks for using our code. 

You can ignore these warnings. The warehouse asset is downloaded from Nuclues, and that can take some time. Can you please ensure that you have a connection to Nuclues and then wait for a while to see if the asset is opened?

**Comment by LTaitLeo** [comment]
I’m encountering exatly the same issue as described here. I can successfully connect to Nucleus, and all assets can be opened manually without any problem. However, when I run viplanner_demo, the process gets stuck here. Any assistance would be greatly appreciated.

**Comment by LTaitLeo** [comment]
I’ve resolved the issue. It turns out that after installing the ViPlanner Omniverse Extension for the first time, a system restart and restarting the Omniverse Launcher were necessary before running the demo.

> I’m encountering exatly the same issue as described here. I can successfully connect to Nucleus, and all assets can be opened manually without any problem. However, when I run viplanner_demo, the process gets stuck here. Any assistance would be greatly appreciated.

**Comment by pascal-roth** [comment]
@LTaitLeo thanks for finding a solution here, not sure why a restart is required.
