### ISSUE TITLE
[Question]Data Collection

### ISSUE THREAD

**Issue by zhw970623** [leggedrobotics/viplanner#46]
### Question
Can you provide an example of a specific command to collect data?

for
./isaaclab.sh -p <path-to-viplanner-repo>/omniverse/standalone/data_collect.py --scene <matterport/carla/warehouse> --num_samples <how-many-viewpoints>

How to set “how-many-viewpoints”

**Comment by pascal-roth** [comment]
For the number of viewpoints you can select any possible number, the default should be 10000 but also less is sufficient for most environments

```
./isaaclab.sh -p /omniverse/standalone/data_collect.py --scene warehouse --num_samples 2000
```
