### ISSUE TITLE
[Question] problem about the model in the hardware depolyment!

### ISSUE THREAD

**Issue by command-z-z** [leggedrobotics/viplanner#52]
### Question
what's the difference of the following two lines of models?
- the first line (L11) is the models officially provided by mmdetection.
- the second line(L12) is the models downloading from your [readme](https://github.com/leggedrobotics/viplanner/blob/main/ros/INSTALL.md#models).
https://github.com/leggedrobotics/viplanner/blob/35a3bea47d423e1d15f38115cb6d1125f60b0f81/ros/planner/config/anymal_c.yaml#L11-L14
however, model architecture and weights appear inconsistent, When I call following class:
https://github.com/leggedrobotics/viplanner/blob/35a3bea47d423e1d15f38115cb6d1125f60b0f81/ros/planner/src/m2f_inference.py#L20-L41
with this error， Do I need to modify anything?
```
The model and loaded state dict do not match exactly

unexpected key in source state_dict: panoptic_head.pixel_decoder.encoder.layers.0.attentions.0.sampling_offsets.weight, panoptic_head.pixel_decoder.encoder.layers.0.attentions.0.sampling_offsets.bias, panoptic_head.pixel_decoder.encoder.layers.0.attentions.0.attention_weights.weight, 
...

missing keys in source state_dict: panoptic_head.pixel_decoder.encoder.layers.0.self_attn.sampling_offsets.weight, panoptic_head.pixel_decoder.encoder.layers.0.self_attn.sampling_offsets.bias, panoptic_head.pixel_decoder.encoder.layers.0.self_attn.attention_weights.weight,
...
```
When i use the model weight provided by `mmdetection`, everything is fine, which makes me wonder.

**Comment by pascal-roth** [comment]
Hi @command-z-z ,

Thanks a lot for using our work. At the time when we did our experiments, the official weights did not fit to the code due to some renaming done in mmdetection, and we had to go some versions back to find the correct model, thus we included it here. Apparently, it is fixed now. You should be able to, therefore, use the latest official weights. 
I hope that answers your question.

**Comment by command-z-z** [comment]
Think you for your reply, my concerns have been resolved.
