### ISSUE TITLE
[Question] Unitree GO2

### ISSUE THREAD

**Issue by IdealQQQ** [leggedrobotics/viplanner#56]
Do you have any configuration files for the legged platform Unitree GO2？I want to run ViPlanner on the LeggedRobot Platform Unitree GO2. Thanks

**Comment by pascal-roth** [comment]
Hi @IdealQQQ,

no, these are not available as we do not have this platform. Please feel free to make a PR once you created them.

**Comment by yhykid** [comment]
@IdealQQQ Hi,bro.Have u tried on Unitree Go2.I planned to try it but im afraid that the Orin NX on Go2 is not enough.Thanks
