### ISSUE TITLE
[Question] cuda error and how to adopt it in real word

### ISSUE THREAD

**Issue by Un1Lee** [leggedrobotics/viplanner#57]
### Question 1

when I run ./isaaclab.sh -p ~/rl_ws/viplanner/omniverse/standalone/viplanner_demo.py --scene carla --model_dir ~/data/carla/

it will report :
GPU | Name                             | Active | 
1   | NVIDIA RTX 5000 Ada Generation   | Yes: 0 
[INFO]: Completed setting up the environment...
File "isaac-sim-4.2.0/exts/omni.isaac.ml_archive/pip_prebundle/torch/nn/modules/conv.py", line 454, in _conv_forward
    return F.conv2d(input, weight, bias, self.stride,
RuntimeError: Expected all tensors to be on the same device, but found at least two devices, cuda:0 and cuda:1! (when checking argument for argument weight in method wrapper_CUDA__cudnn_convolution)

if I add CUDA_VISIBLE_DEVICES=0, so the GPU 0 will be active Yes instead of GPU1.
but 2024-12-11 05:21:55 [1,949ms] [Error] [carb.graphics-vulkan.plugin] Failed to find a graphics and/or presenting queue.

However, when I add CUDA_VISIBLE_DEVICES=1, all is ok, and demo can run successfully.
So could you tell me why CUDA_VISIBLE_DEVICES=0 can not work.

### Question 2

 When I see your code in ominivers dir, I find that where are transform between world and robot(camera).

In simulation, the robot(camera) localization can be get easily.
But in real world, how to get such goal point? I think it is slam. Slam can offer 'world', and localization can offer 'robot(camera)' .
Confused, in your video with real world, I can see nothing about slam.

My question is that in real world, your method need slam or don't? 
If don't, can you help me anything about how it work in real world without slam? Or just tell me what's meaning of goals and obs["planner_image"]["cam_position"] in real world.

Thank you for your help!

**Comment by pascal-roth** [comment]
Hi @Un1Lee,

First of all, thanks for using our work. 

Question 1: 
I am not sure how this is handled on the NVIDIA Isaac side and cannot give an explanation. Please forward that question to the correct channels of NVIDIA Isaac Sim or IsaacLab

Question 2:
The goals in the real world are given in the odom frame and then transformed in the base frame. To complete the this operation, you require some form of state estimator which can be achieved without SLAM (e.g., wheeled odometry or even simpler, by integrating the IMU measurements). With SLAM, the estimation can improve as the drift can be reduced. 
For our work, we ran graph_msf (https://github.com/leggedrobotics/graph_msf) and open3d_slam (https://github.com/leggedrobotics/open3d_slam). 

I hope this answers your question.

**Comment by Un1Lee** [comment]
Oh, I know it now. Thank you so much!
