### ISSUE TITLE
[Bug Report] Bug titleThe model and loaded state dict do not match exactly

### ISSUE THREAD

**Issue by shiwentao12138** [leggedrobotics/viplanner#59]
Hi,I encountered this issue while trying to use VIPlaner:"The model and loaded state dict do not match exactly".  But the .pth file I am using is the pre trained network downloaded from the website recommended in your GitHub article,and the configuration file for the mask2former used is mask2former _r50_8xb2-lsj-50e_coco-panoptic.py.

**Comment by pascal-roth** [comment]
Hi, 
thanks for using our work. I assume you run it on the jetson? Can you make sure that your versions match the ones mentioned in this issue #23

**Comment by shiwentao12138** [comment]
Thank you for your answer. I have found a matching pre training file and resolved this issue.
