### ISSUE TITLE
Dataset Request

### ISSUE THREAD

**Issue by BE-A-HERO** [leggedrobotics/viplanner#7]
Interesting work! May I ask will you release the dataset of the paper?  

This paper use several techniques in training set creation, it would be great if the author can also share the codes of dataset creation process. 

Thanks!!!

**Comment by pascal-roth** [comment]
We are working on it, will be released before ICRA

**Comment by jonyzhang2023** [comment]
> We are working on it, will be released before ICRA

Thanks for your work. And same question.
When will you share the codes of dataset creation process.

**Comment by Xyunze** [comment]
Great work! I'm having trouble finding a way to construct the dataset during training. It would be greatly appreciated if you could share how to process the Matterport dataset.
