### ISSUE TITLE
How to get the depth 

### ISSUE THREAD

**Issue by caiziheng** [leggedrobotics/viplanner#9]
I am very interested in your work, but when I finished reading the article, I didn't find out how you got the depth images. Do you use binocular cameras  or single camera estimation?

**Comment by pascal-roth** [comment]
Hi, 
In simulation, we create the depth image using raycasting. On the real robot, we use IntelSense depth cameras that use stereo depth. I hope this answers your question, otherwise, feel free to reopen this issue.

**Comment by caiziheng** [comment]
thanks
